name = "LJH"
uuid = "d9fa4011-6c11-4e33-b037-fe2237844383"
authors = ["Joe Fowler <drjoefowler@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Nullables = "4d1e1d77-625e-5b40-9113-a560ec7a8ecd"

[compat]
julia = "1.3"
ReferenceMicrocalFiles = "≥0.1.0"

[extras]
ReferenceMicrocalFiles = "cce409be-c91d-11e9-3263-d35f6180a8ba"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ReferenceMicrocalFiles"]
